# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef04a9aa387ba3aac9e42b2a057fdb4edbede0b8ebe77a0890a9ba7941d27dad8b9b9bd239ec3d2a64446cf9c1fe5288d2180fa64cbfab7fdb7d31577eeb262

test:
  secret_key_base: c3676c3d126451f9b9c9c57ad168d7918de0a8e39c63e5711716784cd12b1f52112913283597f5990a9ed7b9b6867b818d036f2a78211d09a0b78015c21ba46f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
